restkv:
  restParams:
    timeout: 10000
    maxValueLength: 1048576      # 1MB
    contentType: "text/plain"
    debug: true
  multithreading:
    serviceThreads: 100
  redis:
    url: "redis://localhost:6379/0"